# -*- coding: utf-8 -*-
"""Field Area Calculation .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AgfrA2m3gEXVD2evhf5a0XgzUHosdUg5
"""

!pip install rasterio

"""Following is a method to calcuate the area of the field captured
Refer here :https://www.dji.com/global/p4-multispectral/specs

---


"""

import math

def calculate_image_area(sensor_width_mm, sensor_height_mm, focal_length_mm, altitude_m):
    # Convert sensor dimensions and focal length to meters
    sensor_width_m = sensor_width_mm / 1000
    sensor_height_m = sensor_height_mm / 1000
    focal_length_m = focal_length_mm / 1000

    # Calculate the image area on the ground
    image_area = (altitude_m * sensor_width_m / focal_length_m) * (altitude_m * sensor_height_m / focal_length_m)

    return image_area

# Camera specifications
effective_pixels = 2.08  # MP
aspect_ratio = 4 / 3.25
image_width = 1600  # pixels
image_height = 1300  # pixels

# Calculate approximate sensor dimensions
sensor_width_mm = (effective_pixels * (aspect_ratio)) ** 0.5
sensor_height_mm = sensor_width_mm / aspect_ratio

rgb_focal_length_mm = 5.74
altitude_m = 383.0  # This has to be provided as input which is found using properties of image of Multispectral image

# Calculate the area covered by the RGB sensor
rgb_area = calculate_image_area(sensor_width_mm, sensor_height_mm, rgb_focal_length_mm, altitude_m)
print("Estimated area covered by RGB sensor:", rgb_area, "square meters")